services:
  backend:
    build: .
    ports:
      - "8036:8036"
    environment:
      # Conexión a MongoDB usando el nombre del servicio 'mongo'
      - CONNECTION_DB=mongodb://posdbs:JDDok45h674830hfusORtwWW4fdf65B@mongo:27017/posdbs-?authSource=admin
      - SPRING_DATA_MONGODB_URI=mongodb://posdbs:JDDok45h674830hfusORtwWW4fdf65B@mongo:27017/posdb?authSource=admin
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=posdb
      - TZ=America/Caracas
    depends_on:
      mongo:
        condition: service_healthy   # espera a que mongo esté sano
    networks:
      - pos-network

  mongo:
    image: mongo:latest
    container_name: mongopos
    ports:
      - "12876:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=posdbs
      - MONGO_INITDB_ROOT_PASSWORD=JDDok45h674830hfusORtwWW4fdf65B
      - MONGO_INITDB_DATABASE=posdb   # opcional: crea la base de datos al inicio
      - TZ=America/Caracas
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
      - /.uploads:/app/uploads
    networks:
      - pos-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--username", "posdbs", "--password", "JDDok45h674830hfusORtwWW4fdf65B"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo-data:
  mongo-config:

networks:
  pos-network:
    driver: bridge