spring.application.name=pos
#server.port=8080
server.port=8067
#spring.data.mongodb.uri=mongodb://cvmdbs:JDDok45h674830hfusORtwWW4fdf65B@157.180.82.23:27017/pos_db?authSource=admin
spring.data.mongodb.uri=mongodb://localhost:27017/pos_db?authSource=admin
#spring.jackson.serialization.write-dates-as-timestamps=false
logging.level.root=INFO
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration